name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C compiler
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Run script to test unsigned int and unsigned long sizes
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          chmod +x test_sizes.sh
          ./test_sizes.sh ${{ matrix.os }}

      - name: Run PowerShell script to test unsigned int and unsigned long sizes
        shell: pwsh
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          .\test_sizes.ps1 ${{ matrix.os }}
